/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A condition expression
 */
export interface Conditions {
  /**
   * All conditions in this list must be met
   */
  and?: Conditions1[];
  /**
   * Any conditions in this list must be met
   */
  or?: Conditions1[];
  not?: Conditions1;
}
/**
 * A condition expression
 */
export interface Conditions1 {
  /**
   * All conditions in this list must be met
   */
  and?: Conditions1[];
  /**
   * Any conditions in this list must be met
   */
  or?: Conditions1[];
  not?: Conditions1;
}
