/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A CSS selector expression selecting the DOM nodes that should get processed
 */
export type DOMMatchExpression = string;
/**
 * A CSS selector expression selecting the Markdown nodes that should get processed
 */
export type MDASTMatchExpression = string;
/**
 * An [Express-like](https://expressjs.com/en/guide/routing.html) path expression for selecting URL patterns that will apply the changes to the `body` element.
 */
export type URLPatternMatchExpression = string;
/**
 * Use a [Content Intelligence](https://github.com/adobe/helix-pipeline/blob/master/README.md#infer-content-types-with-utilstypes) expression for selecting sections in MDAST that have the specified order of children.
 */
export type ContentIntelligenceMatchExpression = string;

export interface MarkupMapping {
  /**
   * The (optional) name of the mapping. The name is normative only, and can be used for debugging purposes. It does not affect either matching nor the markup output.
   */
  name?: string;
  match: (DOMMatchExpression | MDASTMatchExpression | URLPatternMatchExpression | ContentIntelligenceMatchExpression) &
    string;
  type?: "html" | "markdown" | "url" | "content";
  /**
   * Add the following HTML tags around the generated HTML. This attribute is using [Emmet](https://emmet.io) notation.
   */
  wrap?: string;
  /**
   * Add the following HTML tags instead of the generated HTML. This attribute is using [Emmet](https://emmet.io) notation.
   */
  replace?: string;
  /**
   * Add the following class names to the `class` attribute of the generated HTML
   */
  classnames?: string[];
  /**
   * create new attributes for each key value pair below this property
   */
  attribute?: {
    /**
     * The property value
     */
    [k: string]: string;
  };
}
