/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines the target URL where content should be retrieved from.
 */
export type MountPoint =
  | string
  | {
      url: string;
      /**
       * Specifies the fallback path if the requested item cannot be found. The fallback path is relative to the basepath of the item originally requested, so if the requested item is `/foo/bar.md` and the `fallbackPath` is `baz.md`, then `/foo/baz.md` will be the fallback item.
       */
      fallbackPath?: string;
      /**
       * encrypted credentials.
       */
      credentials?: string[];
      [k: string]: unknown;
    };
