/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Representation of a origin host for a proxy strain.
 */
export interface Origin {
  /**
   * The hostname of the backend.
   */
  hostname?: string;
  /**
   * The port number.
   */
  port?: number;
  error_threshold?: number;
  /**
   * How long to wait for the first bytes in milliseconds.
   */
  first_byte_timeout?: number;
  /**
   * Weight used to load balance this backend against others.
   */
  weight?: number;
  /**
   * An hostname, IPv4, or IPv6 address for the backend.
   */
  address?: string;
  /**
   * How long to wait for a timeout in milliseconds.
   */
  connect_timeout?: string;
  /**
   * The name of the backend.
   */
  name?: string;
  /**
   * How long to wait between bytes in milliseconds.
   */
  between_bytes_timeout?: number;
  /**
   * The shield POP designated to reduce inbound load on this origin by serving the cached data to the rest of the network.
   */
  shield?: string;
  /**
   * Overrides ssl_hostname, but only for cert verification. Does not affect SNI at all.
   */
  ssl_cert_hostname?: string;
  /**
   * Maximum number of connections.
   */
  max_conn?: number;
  /**
   * Whether or not to use SSL to reach the backend.
   */
  use_ssl?: boolean;
  /**
   * The base path to make requests again. For example, if your `origin` is `http://www.example.com/foo` and a request is made to your site using the URL `/bar`, a backend request to `http://www.example.com/foo/bar` will be made.
   */
  path?: string;
  /**
   * The hostname to override the [Host header](https://docs.fastly.com/guides/basic-configuration/specifying-an-override-host).
   * By default, proxy strains use the `Host` header that was used to make the request to Helix's CDN, which is ideal for migration use cases where the existing backend expects to serve traffic to a hostname that has now been taken over by Helix. In cases where Helix is aggregating content from multiple hosts, and the backend won't serve any content to the domain name Helix is using, set the `override_host` property to an accepted `Host` header value.
   */
  override_host?: string;
}
