/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Performance testing details.
 */
export interface Performance {
  /**
   * Testing device
   */
  device?:
    | ""
    | "MotorolaMotoG4"
    | "iPhone5"
    | "iPhone6"
    | "iPhone6Plus"
    | "iPhone7"
    | "iPhone8"
    | "Nexus5X"
    | "Nexus6P"
    | "GalaxyS5"
    | "iPad"
    | "iPadPro";
  /**
   * Testing location
   */
  location?:
    | ""
    | "NorthVirginia"
    | "Frankfurt"
    | "Sydney"
    | "Ohio"
    | "California"
    | "Oregon"
    | "Canada"
    | "Ireland"
    | "Tokyo"
    | "Seoul"
    | "Singapore"
    | "Mumbai"
    | "SaoPaulo"
    | "London";
  /**
   * Testing connection
   */
  connection?:
    | ""
    | "regular2G"
    | "good2G"
    | "slow3G"
    | "regular3G"
    | "good3G"
    | "emergingMarkets"
    | "regular4G"
    | "LTE"
    | "dsl"
    | "wifi"
    | "cable";
  /**
   * Lighthouse SEO Score
   */
  "lighthouse-seo-score"?: number;
  /**
   * Lighthouse Best Practices Score
   */
  "lighthouse-best-practices-score"?: number;
  /**
   * Lighthouse Accessibility Score
   */
  "lighthouse-accessibility-score"?: number;
  /**
   * Lighthouse Performance Score
   */
  "lighthouse-performance-score"?: number;
  /**
   * Lighthouse Progressive Web App Score
   */
  "lighthouse-pwa-score"?: number;
  /**
   * JS Parse & Compile
   */
  "js-parse-compile"?: number;
  /**
   * DOM Element Count
   */
  "dom-size"?: number;
  /**
   * 85% Visually Complete
   */
  visually_complete_85?: number;
  /**
   * Visually Complete
   */
  visually_complete?: number;
  /**
   * Time to Interactive
   */
  "consistently-interactive"?: number;
  /**
   * First CPU Idle
   */
  "first-interactive"?: number;
  /**
   * Time to First Byte
   */
  "time-to-first-byte"?: number;
  /**
   * Estimated input latency
   */
  "estimated-input-latency"?: number;
  /**
   * Speed Index
   */
  speed_index?: number;
  /**
   * First Meaningful Paint
   */
  "first-meaningful-paint"?: number;
  /**
   * First Contentful Paint
   */
  "first-contentful-paint"?: number;
  /**
   * First Paint
   */
  firstRender?: number;
  /**
   * Total Image size in bytes
   */
  image_body_size_in_bytes?: number;
  /**
   * Total Image transferred
   */
  image_size_in_bytes?: number;
  /**
   * Total Webfont size in bytes
   */
  font_body_size_in_bytes?: number;
  /**
   * Total Webfont transferred
   */
  font_size_in_bytes?: number;
  /**
   * Total JavaScript size in bytes
   */
  js_body_size_in_bytes?: number;
  /**
   * Total JavaScript Transferred
   */
  js_size_in_bytes?: number;
  /**
   * Total CSS size in bytes
   */
  css_body_size_in_bytes?: number;
  /**
   * Total CSS transferred
   */
  css_size_in_bytes?: number;
  /**
   * Total HTML size in bytes
   */
  html_body_size_in_bytes?: number;
  /**
   * Total HTML transferred
   */
  html_size_in_bytes?: number;
  /**
   * Response time
   */
  page_wait_timing?: number;
  /**
   * Total Page transferred
   */
  page_size_in_bytes?: number;
  /**
   * Total Page size in bytes
   */
  page_body_size_in_bytes?: number;
  /**
   * Number of requests
   */
  asset_count?: number;
  /**
   * onLoad
   */
  onload?: number;
  /**
   * onContentLoad
   */
  oncontentload?: number;
}
