/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Property = SingleValueProperty | MultiValueProperty;

/**
 * The property in an index. The value will be stored as a single cardinal value.
 */
export interface SingleValueProperty {
  /**
   * A CSS selector expression that selects nodes in the HTML (DOM) or Markdown (MDAST) syntax tree
   */
  select: string;
  /**
   * A ES6 template literal expression that extracts the value from the matching node(s) to be stored in the index
   */
  value: string;
  /**
   * Whether to enable faceted search on this property
   */
  faceted?: boolean;
}
/**
 * The property in an index. The value will be stored as a list of values
 */
export interface MultiValueProperty {
  /**
   * A CSS selector expression that selects nodes in the HTML (DOM) or Markdown (MDAST) syntax tree
   */
  select: string;
  /**
   * A ES6 template literal expression that extracts the values from the matching nodes to be stored in the index
   */
  values: string;
  /**
   * Whether to enable faceted search on this property
   */
  faceted?: boolean;
}
