/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A named query that can be run against an index
 */
export interface Query {
  /**
   * The base query to run. If the value is an object or array, use [QBL JSON or YAML notation](https://github.com/adobe/helix-querybuilder#as-json-or-yaml)
   */
  query?:
    | string
    | {
        [k: string]: unknown;
      }
    | unknown[];
  /**
   * How many hits each page of search results should contain
   */
  hitsPerPage?: number;
  /**
   * How long (in seconds) search results should be cached on the CDN
   */
  cache?: number;
  /**
   * Which URL parameters to accept in the query when served on the web
   */
  parameters?: string[];
  /**
   * An ES6 template expression that determines which filters to apply
   */
  filters?: string;
  [k: string]: unknown;
}
