/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A strain is a combination of code and content that enables the creation of a digital experience. Strains can be used to create language variants of websites, A/B tests, personalization, or to aggregate content from multiple sources
 */
export interface RedirectRule {
  /**
   * A URL path or regular expression to match the path of a URL. It can contain capture groups that can be used in `to`.
   */
  from?: string;
  /**
   * A replacement string that replaces matched URLs found in `from`.
   */
  to?: string;
  /**
   * What kind of redirect is this?
   */
  type?: "permanent" | "temporary" | "internal";
}
