/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A JSON representation of an Excel or Google Sheets data row.
 */
export interface Row {
  /**
   * Value of the cell in the given column.
   */
  [k: string]: string | number;
}
