/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The source resource path to get records from. These records should at least contain a path property.
 */
export type Source = string;
/**
 * The destination resource path to store sitemap to.
 */
export type Path = string;
/**
 * The HREF language to use when listing alternates.
 */
export type HREFLanguage = string;
/**
 * How to compute the respective path in that language. If not present, paths do not contain a language specific part.
 */
export type Alternate = string;

export interface SitemapLanguage {
  source?: Source;
  destination: Path;
  hreflang: HREFLanguage;
  alternate?: Alternate;
  [k: string]: unknown;
}
