/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The source resource path to get records from. These records should at least contain a path property.
 */
export type Source = string;
/**
 * The origin to prepend to paths found in the source.
 */
export type Origin = string;
/**
 * The destination resource path to store sitemap to.
 */
export type Path = string;
/**
 * The format to use for last modification of a location. If not present, no last modification is added.
 */
export type Lastmod = string;
/**
 * The source resource path to get records from. These records should at least contain a path property.
 */
export type Source1 = string;
/**
 * The destination resource path to store sitemap to.
 */
export type Path1 = string;
/**
 * The HREF language to use when listing alternates.
 */
export type HREFLanguage = string;
/**
 * How to compute the respective path in that language. If not present, paths do not contain a language specific part.
 */
export type Alternate = string;

export interface Sitemap {
  source?: Source;
  origin?: Origin;
  destination?: Path;
  lastmod?: Lastmod;
  languages?: SitemapLanguages;
  [k: string]: unknown;
}
/**
 * The languages to add to the sitemap
 */
export interface SitemapLanguages {
  [k: string]: SitemapLanguage;
}
export interface SitemapLanguage {
  source?: Source1;
  destination: Path1;
  hreflang: HREFLanguage;
  alternate?: Alternate;
  [k: string]: unknown;
}
