/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Representation of the fragments of a Git URL
 */
export interface GitURL {
  /**
   * The protocol to access the Git repository
   */
  protocol?: "https" | "http" | "ssh";
  /**
   * The hostname without port
   */
  hostname?: string;
  /**
   * The hostname with port
   */
  host?: string;
  /**
   * The port to access the Git Repository
   */
  port?: number | string;
  /**
   * The owner or username that the repository belongs to
   */
  owner: string;
  /**
   * The path within the repository
   */
  path?: string;
  /**
   * The repository name
   */
  repo: string;
  /**
   * The branch, tag, or sha of the tree in the repository to use
   */
  ref: string;
  /**
   * List of white listed paths
   */
  allow?: string[];
  /**
   * List of white listed paths
   */
  deny?: string[];
  /**
   * Deprecated: Enable server-side asset processing.
   */
  magic?: boolean;
}
