/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The source representation to be used by the indexer to extract values
 */
export type Source = "html" | "markdown";

export interface VanityURLMapping {
  source?: Source;
  /**
   * The source document to retrieve values from. Known variables in the URI Template are: `repo`, `ref`, `owner`, `path`
   */
  fetch?: string;
  /**
   * A CSS selector expression that selects nodes in the HTML (DOM) or Markdown (MDAST) syntax tree
   */
  select?: string;
  /**
   * A ES6 template literal expression that extracts the value from the matching node(s) to be stored in the index
   */
  value?: string;
  [k: string]: unknown;
}
